profile="dev"

[server]
address="0.0.0.0:18080"

[tracing]
max_level="TRACE"
directory="./logs"
with_file=false

[database]
sources = [
    { url = "sqlite://sqlite.db?mode=rwc" , max_connections=5 }
]
replicas = [
    { url = "sqlite://sqlite.db" , max_connections=5 },
    { url = "sqlite://sqlite.db" , max_connections=5 }
]

[redis]
enable=true
host="0.0.0.0"
port=6379